# 💐💚 coder-images: Optimized, and easy Docker images and Coder templates to use in your everyday work!
# Copyright (c) 2022 Noel <cutie@floofy.dev>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

name: Release Pipeline
on:
  release:
    types: [published]
jobs:
  release:
    name: Release Pipeline
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      fail-fast: true
      matrix:
        platform:
          - runner: ubuntu-latest
            suffix: amd64
            buildx: true
          - runner: self-hosted
            suffix: arm64
            buildx: false
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Docker Buildx
      if: ${{ matrix.platform.buildx == true }}
      uses: docker/setup-buildx-action@v2

    - name: Login into GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: auguwu
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: "[images/base] Build and push for platform linux/${{ matrix.platform.suffix }}"
      uses: docker/build-push-action@v3
      with:
        context: images/base
        file: ${{ matrix.platform.suffix }}.Dockerfile
        platforms: linux/${{ matrix.platform.suffix }}
        tags: |
          ghcr.io/auguwu/coder-images/base:latest-${{ matrix.platform.suffix }}

  manifests:
    name: Apply Docker manifests
    runs-on: ubuntu-latest
    needs: [release]
    steps:
    - name: Login into GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: auguwu
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Apply manifests
      uses: Noelware/docker-manifest-action@master
      with:
        push: true
        base-image: ghcr.io/auguwu/coder-images/base:latest
        extra-images: |
          ghcr.io/auguwu/coder-images/base:latest-amd64,
          ghcr.io/auguwu/coder-images/base:latest-arm64
